#!/bin/bash

echo ""
echo "--------------------------------------------------------------------------------"
echo "Deploying thomas-mcevoy.com-nuxt with the following commit message:"
echo "'$1'"
echo "--------------------------------------------------------------------------------"

npm run build

git add .
git commit -m "$1"
git push

ssh tom@68.183.30.7 "cd thomas-mcevoy.com-nuxt &&
git pull &&
npm run prod"